name: Nix
on:
  pull_request:
  push:
    branches: [master]

jobs:
  lints:
    name: Build and Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .
      - name: Run `nix flake check`
        run: nix flake check

  build:
    name: Build with ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ghc94, ghc98]
        experimental: [false]
        # include:
        #   - compiler: ghc92
        #     experimental: true
        #   - compiler: ghc910
        #     experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix build for ${{ matrix.compiler }}
        run: nix build .#${{ matrix.compiler }}-taffybar
